import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Scanner;

/**
 * A simple employee class that can be read or written in binary format.
 */
public class Employee implements Serializable {
    /**
     * An serialization ID generated by Eclipse.
     */
    private static final long serialVersionUID = 6714812365672432585L;

    /**
     * An unique ID for each employee.
     */
    private int id;

    /**
     * Name of the employee. The name is assumed to be shorter than
     * 15-characters.
     */
    private String name;

    /**
     * The salary for the employee rounded to the nearest dollar.
     */
    private int salary;

    /**
     * A simple constructor to create employee objects.
     * 
     * @param id     The ID to be associated with the employee.
     * @param name   The name of the employee.
     * @param salary The salary for the employee.
     */
    public Employee(int id, String name, int salary) {
        this.id = id;
        this.name = name;
        this.salary = salary;
    }

    @Override
    public String toString() {
        return String.format("%2d, %-15s, %6d", id, name, salary);
    }

    /**
     * Helper method to load employee data from a given text file and return the
     * information as an array of Employee objects.
     * 
     * @param txtFileName Path to the CSV file from where employee data is to be
     *                    read.
     * @return An array of Employee objects created using the data from the CSV
     *         file.
     * @throws FileNotFoundException Exposes exception.
     */
    public static Employee[] load(String txtFileName)
            throws FileNotFoundException {
        // ArrayList to hold the employees
        ArrayList<Employee> list = new ArrayList<Employee>();
        // Use a scanner to read line-by-line and use
        Scanner fileReader = new Scanner(new File(txtFileName));
        while (fileReader.hasNextLine()) {
            // create an employee given info from the file
            String employee = fileReader.nextLine();
            // String.split(",") to split data into 3 columns.
            String[] id = employee.split(",");
            // create a new employee and add it to the list
            list.add(new Employee((Integer.parseInt(id[0])), id[1],
                    Integer.parseInt(id[2])));
        }

        // close scanner
        fileReader.close();
        // return an array of the employees from the list
        Employee[] ls = new Employee[list.size()];
        return list.toArray(ls);
    }

    /**
     * Writes the supplied array to a given file in binary format using an
     * ObjectOutputStream.
     * 
     * @note This method should not have any loops
     * 
     * @param outFileName Path to the output file.
     * @param list        The array of employees to be written
     * @throws IOException Exceptions may be throws due to I/O errors.
     */
    public static void writeAsBinary(String outFileName, Employee[] list)
            throws IOException {
        ObjectOutputStream output = new ObjectOutputStream(
                new FileOutputStream(outFileName));
        output.writeObject(list);
    }

    /**
     * Reads an array of employees from a binary file using an
     * ObjectInputStream.
     * 
     * @note This method assumes that the binary data has been written using the
     *       writeAsBinary method in this class.
     * 
     * @param inFileName The binary file from where data is to be read.
     * @return An array of Employee objects read from the file.
     * @throws IOException            Exceptions may be throws due to I/O
     *                                errors.
     * @throws ClassNotFoundException If object was not array of Employee
     */
    public static Employee[] readAsBinary(String inFileName)
            throws IOException, ClassNotFoundException {
        ObjectInputStream input = new ObjectInputStream(
                new FileInputStream(inFileName));
        Object employee = input.readObject();
        return (Employee[]) employee;
    }
}
